### ISSUE TITLE
Sleep problems

### ISSUE THREAD

**Issue by mogul9** [the-Quert/XPS-9360-macOS#29]
Hello, quert.thank you for your hard work, let us use the latest system and the most stable boot file. My computer configuration is the same as yours. However, after the recent reinstallation, there was a problem that the monitor could not sleep and wake up after sleep (cpu is still running at high load), so I tried a lot of efi and system versions, but failed to solve them. Does this question have anything to do with bios or hardware? How should I solve it? Thank you again and wish you a happy life. Your fans.

**Comment by ghost** [comment]
Please make sure the bios settings is same as the guide provided.
And follow the [undervolting](https://github.com/the-Quert/XPS-9360-macOS#cpu-undervolting) part in the guide.

The frequency of CPU would remain 0.8GHz, but after sleeping, it remains at about 0.99-1.2GHz when idle.
The problem of CPU frequency is because of HWP settings lost after wake up from sleeping, this problem would be improve in few weeks.

- Kinda busy on other stuffs these days, more researches would keep going in few days.

- Feel free to report any issues, and maybe I will do it tomorrow.

**Comment by ghost** [comment]
`OpenCore` is just modified and updated.
Try `OpenCore` as bootloader,  cause more detailed power management is just configured with `DSDT` in OC.

- Feel free to report any issues, and maybe I will do it tomorrow.

**Comment by theQuert** [comment]
Problem is not traced anymore, case closed.
