### ISSUE TITLE
ISO aren't bootable

### ISSUE THREAD

**Issue by rsuchwani** [the-Quert/XPS-9360-macOS#4]
Hello,

So I downloaded the iso for 10.14.6 with all the clover files in it, used Etcher to write the iso on the USB, but the final USB isn't bootable. 

What I'm missing?

**Comment by ghost** [comment]
Have you add Boot Entry with path "/EFI/EFI/CLOVER/CLOVERX64.efi" in BIOS ?
It should work after you add the correct path in BIOS.

**Comment by rsuchwani** [comment]
Hi,

Yes, I did and that's the screen I'm presented with. (Please see the
attached)
![IMG_20190919_212310](https://user-images.githubusercontent.com/54313874/65263556-4edf2d80-db26-11e9-8a1a-d46351d5232b.jpg)

**Comment by ghost** [comment]
Which version of 10.14.6 you are testing ?
Check the MD5 if there is same as I note.

**Comment by rsuchwani** [comment]
This one, and the MD5 Checksum is matching

https://drive.google.com/file/d/1IlLJ6v556RYNmjHKNmUFkWJ2xrT0rGLn/view?usp=drivesdk

Can you please confirm the process?
Download .DMG > Use Etcher to Flash on USB > Boot from USB

I did that, added entries in Bios too, but as shown in the screen capture, there isn't any menu for the Grub/Shell to alter variables and no installer.

What I'm missing?

**Comment by ghost** [comment]
After testing, there are something wrong with the macOS installer part, Clover works normally.

The images below are un-bootable:
1. macOS Mojave 10.14.6(18G87) Installer with Clover 5033.dmg
2. macOS Mojave 10.14.6(18G95) Installer with Clover 5058.dmg

To install macOS Mojave 10.14.6, use with the ISO below: 
# macOS Mojave 10.14.6(18G84) Installer with Clover 5027.dmg

There is allowed to install 10.14.6(18G84), then update to 10.14.6(18G95)

Since 18G87 and 18G95 are un-bootable for now, the two versions will be delete from repository and GDrive.
ISO for 18G87 and 18G95 will be testing and uploading in one week.

**Comment by the-Quert** [comment]
Since 18G87 and 18G95 are un-bootable, the two versions will be delete from repository and GDrive. 

ISO for 18G87 and 18G95 will be testing and uploading in one week.

**Comment by rsuchwani** [comment]
Alright, that's understandable. Closing the issue now. Thanks for all the assistance.

**Comment by ghost** [comment]
Download Link and tutorial are provided in the repo:
https://github.com/the-Quert/XPS-9360-macOS#create-bootable-usb-installer
